name: CI
on: [push, pull_request]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: check out repository code
        uses: actions/checkout@v2
      - name: setup environment & run cross validation
        run:  |
          source setup_env.sh
          python3 scripts/test.py testing_inputs/samples.dat
