name: CI
on: [push, pull_request]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: check out repository code
        uses: actions/checkout@v2
      - name: setup environment
        run: source setup_env.sh
      - name: run cross validation
        run: python3 scripts/test.py testing_inputs/samples.dat
