name: CI
on: [push, pull_request]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: check out repository code
        uses: actions/checkout@v2
      - name: install packages
        run: xargs sudo apt install < ubuntu_requirements.txt
      - name: run cross validation
        run: python3 scripts/test.py testing_inputs/samples.dat
